image: php:7.1.1

definitions:
  steps:
    - step: &unit-test
        name: Unit Test
        caches:
            - composer
        script:
            - echo "Running Unit Test"
    - step: &deploy-test
        name: Deploy to Test
        caches:
            - composer
        script:
            - echo "Deploying to Test"
    - step: &e2e-test
        name: End-to-End Test
        caches:
            - node
        script:
            - echo "Running End-to-End Test"

pipelines:
  pull-requests:
    '**': #this runs as default for any branch not elsewhere defined
      - step: *unit-test
    develop:
      - step: *unit-test
      - step: *deploy-test
      - step: *e2e-test
    hotfix/*:
      - step: *unit-test
      - step: *deploy-test
      - step: *e2e-test
  branches:
    master: # Test, Build and Deploy
       - step: *unit-test
       - step: *deploy-test
       - step: *e2e-test
       - step:
          name: Deploy to Production
          trigger: manual
          deployment: production
          caches:
            - composer
          script:
            - echo "Deploying to Production"
            # - npm run deploy
            # - npm run test:e2e
            - sh ./build/shell/install-packages.sh
            - sh ./build/shell/post-deploy.sh
